[format]
line-width = 120
indent-width = 2
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = true
exclude = ["data/"]
default-exclude = true
skip = []
table = []
default-table = true
